/// Flutter icons RealState
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RealState
///      fonts:
///       - asset: fonts/RealState.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RealState {
  RealState._();

  static const _kFontFam = 'RealState';
  static const String? _kFontPkg = null;

  static const IconData cross = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_date = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_3181 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData letter_unread = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pending = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_calling_rounded = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow_filled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_rounded = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
